export const dummySkills: SkillRecord[] = [
	{
		id: "1",
		title: "React Fundamentals",
		slug: "react-fundamentals",
		description:
			"Basic concepts of React including components, props, and state.",
		category: "frontend",
		tags: ["react", "javascript", "frontend"],
		installCommand: "npm install react react-dom",
		createdAt: "2026-04-01T10:00:00Z",
		authorClerkId: "user_123",
		authorEmail: "react@example.com",
	},
	{
		id: "2",
		title: "Go REST API",
		slug: "go-rest-api",
		description: "Building RESTful APIs using Go and net/http.",
		category: "backend",
		tags: ["golang", "api", "backend"],
		installCommand: "go get github.com/gin-gonic/gin",
		createdAt: "2026-04-02T11:00:00Z",
		authorClerkId: "user_456",
		authorEmail: "go@example.com",
	},
	{
		id: "3",
		title: "PostgreSQL Basics",
		slug: "postgresql-basics",
		description: "Introduction to PostgreSQL queries and schema design.",
		category: "database",
		tags: ["postgresql", "sql", "database"],
		installCommand: "brew install postgresql",
		createdAt: "2026-04-03T12:00:00Z",
		authorClerkId: "user_789",
		authorEmail: "db@example.com",
	},
	{
		id: "4",
		title: "Docker Essentials",
		slug: "docker-essentials",
		description: "Learn how to containerize applications using Docker.",
		category: "devops",
		tags: ["docker", "containers", "devops"],
		installCommand: "docker pull node:18",
		createdAt: "2026-04-04T13:00:00Z",
		authorClerkId: "user_321",
		authorEmail: "docker@example.com",
	},
	{
		id: "5",
		title: "TypeScript Advanced Types",
		slug: "typescript-advanced-types",
		description: "Deep dive into generics, unions, and advanced typing.",
		category: "frontend",
		tags: ["typescript", "advanced", "types"],
		installCommand: "npm install typescript",
		createdAt: "2026-04-05T14:00:00Z",
		authorClerkId: "user_654",
		authorEmail: "ts@example.com",
	},
];
